/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class Project extends javax.swing.JFrame{

    private Graphics g3D;
    private int step = 40; // Ti le: 1 don vi = 40 pixel 
    private int height; // Chieu cao cua Panel
    private int width; // Chieu dai cua Panel
    
    
    public Project() {
        initComponents();
        this.setLocationRelativeTo(null);
        height = panel3D.getBounds().height;
        width = panel3D.getBounds().width;
        
        g3D = panel3D.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panel3D = new javax.swing.JPanel();
        xoaManHinh_Btn = new javax.swing.JButton();
        tuyChon_LPn = new javax.swing.JLayeredPane();
        tuyChon_Pn = new javax.swing.JPanel();
        HLP_Btn = new javax.swing.JButton();
        HHCN_Btn = new javax.swing.JButton();
        HLP_Pn = new javax.swing.JPanel();
        doDaiCanhHLP_Lbl = new javax.swing.JLabel();
        veHLP_Btn = new javax.swing.JButton();
        doDaiCanhHLP_TF = new javax.swing.JTextField();
        quayLai_Btn1 = new javax.swing.JButton();
        diemGocHLP_Lbl = new javax.swing.JLabel();
        xOHLP_TF = new javax.swing.JTextField();
        xOHLP_Lbl = new javax.swing.JLabel();
        yOHLP_Lbl = new javax.swing.JLabel();
        yOHLP_TF = new javax.swing.JTextField();
        zOHLP_Lbl = new javax.swing.JLabel();
        zOHLP_TF = new javax.swing.JTextField();
        HHCN_Pn = new javax.swing.JPanel();
        rong_TF = new javax.swing.JTextField();
        cao_Lbl = new javax.swing.JLabel();
        dai_TF = new javax.swing.JTextField();
        dai_Lbl = new javax.swing.JLabel();
        cao_TF = new javax.swing.JTextField();
        rong_Lbl = new javax.swing.JLabel();
        veHHCN_Btn = new javax.swing.JButton();
        quayLai_Btn = new javax.swing.JButton();
        diemGocHHCN_Lbl = new javax.swing.JLabel();
        xOHHCN_Lbl = new javax.swing.JLabel();
        xOHHCN_TF = new javax.swing.JTextField();
        yOHHCN_Lbl = new javax.swing.JLabel();
        yOHHCN_TF = new javax.swing.JTextField();
        zOHHCN_Lbl = new javax.swing.JLabel();
        zOHHCN_TF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel3D.setBackground(new java.awt.Color(255, 255, 255));
        panel3D.setPreferredSize(new java.awt.Dimension(900, 300));
        panel3D.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel3DAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panel3DLayout = new javax.swing.GroupLayout(panel3D);
        panel3D.setLayout(panel3DLayout);
        panel3DLayout.setHorizontalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panel3DLayout.setVerticalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        xoaManHinh_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xoaManHinh_Btn.setText("Xóa màn hình");
        xoaManHinh_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaManHinh_BtnActionPerformed(evt);
            }
        });

        tuyChon_LPn.setLayout(new java.awt.CardLayout());

        HLP_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HLP_Btn.setText("Hình lập phương");
        HLP_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HLP_BtnActionPerformed(evt);
            }
        });

        HHCN_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HHCN_Btn.setText("Hình hộp chữ nhật");
        HHCN_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HHCN_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tuyChon_PnLayout = new javax.swing.GroupLayout(tuyChon_Pn);
        tuyChon_Pn.setLayout(tuyChon_PnLayout);
        tuyChon_PnLayout.setHorizontalGroup(
            tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuyChon_PnLayout.createSequentialGroup()
                .addGroup(tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HHCN_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(HLP_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tuyChon_PnLayout.setVerticalGroup(
            tuyChon_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuyChon_PnLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(HHCN_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(HLP_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        tuyChon_LPn.add(tuyChon_Pn, "card4");

        doDaiCanhHLP_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doDaiCanhHLP_Lbl.setText("Độ dài cạnh HLP");

        veHLP_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        veHLP_Btn.setText("Vẽ hình lập phương");
        veHLP_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veHLP_BtnActionPerformed(evt);
            }
        });

        doDaiCanhHLP_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        quayLai_Btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quayLai_Btn1.setText("Quay lại");
        quayLai_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLai_Btn1ActionPerformed(evt);
            }
        });

        diemGocHLP_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diemGocHLP_Lbl.setText("Điểm gốc");

        xOHLP_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xOHLP_TF.setText("0");

        xOHLP_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xOHLP_Lbl.setText("xO");

        yOHLP_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yOHLP_Lbl.setText("yO");

        yOHLP_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yOHLP_TF.setText("0");

        zOHLP_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        zOHLP_Lbl.setText("zO");

        zOHLP_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zOHLP_TF.setText("0");

        javax.swing.GroupLayout HLP_PnLayout = new javax.swing.GroupLayout(HLP_Pn);
        HLP_Pn.setLayout(HLP_PnLayout);
        HLP_PnLayout.setHorizontalGroup(
            HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HLP_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doDaiCanhHLP_TF)
                    .addComponent(veHLP_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HLP_PnLayout.createSequentialGroup()
                        .addGroup(HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doDaiCanhHLP_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diemGocHLP_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HLP_PnLayout.createSequentialGroup()
                                .addGroup(HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(xOHLP_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(xOHLP_TF, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(yOHLP_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yOHLP_TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(zOHLP_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(zOHLP_TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(quayLai_Btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        HLP_PnLayout.setVerticalGroup(
            HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HLP_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diemGocHLP_Lbl)
                .addGap(7, 7, 7)
                .addGroup(HLP_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HLP_PnLayout.createSequentialGroup()
                        .addComponent(xOHLP_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xOHLP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HLP_PnLayout.createSequentialGroup()
                        .addComponent(yOHLP_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yOHLP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HLP_PnLayout.createSequentialGroup()
                        .addComponent(zOHLP_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zOHLP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doDaiCanhHLP_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doDaiCanhHLP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(veHLP_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quayLai_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tuyChon_LPn.add(HLP_Pn, "card2");

        rong_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cao_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cao_Lbl.setText("Cao");

        dai_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dai_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dai_Lbl.setText("Dài");

        cao_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        rong_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rong_Lbl.setText("Rộng");

        veHHCN_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        veHHCN_Btn.setText("Vẽ hình hộp chữ nhật");
        veHHCN_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veHHCN_BtnActionPerformed(evt);
            }
        });

        quayLai_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quayLai_Btn.setText("Quay lại");
        quayLai_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLai_BtnActionPerformed(evt);
            }
        });

        diemGocHHCN_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diemGocHHCN_Lbl.setText("Điểm gốc");

        xOHHCN_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xOHHCN_Lbl.setText("xO");

        xOHHCN_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xOHHCN_TF.setText("0");

        yOHHCN_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yOHHCN_Lbl.setText("yO");

        yOHHCN_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yOHHCN_TF.setText("0");

        zOHHCN_Lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        zOHHCN_Lbl.setText("zO");

        zOHHCN_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zOHHCN_TF.setText("0");

        javax.swing.GroupLayout HHCN_PnLayout = new javax.swing.GroupLayout(HHCN_Pn);
        HHCN_Pn.setLayout(HHCN_PnLayout);
        HHCN_PnLayout.setHorizontalGroup(
            HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HHCN_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veHHCN_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quayLai_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cao_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rong_TF)
                    .addComponent(cao_TF)
                    .addComponent(dai_TF)
                    .addGroup(HHCN_PnLayout.createSequentialGroup()
                        .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diemGocHHCN_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dai_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rong_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HHCN_PnLayout.createSequentialGroup()
                                .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(xOHHCN_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(xOHHCN_TF, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(yOHHCN_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yOHHCN_TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(zOHHCN_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(zOHHCN_TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HHCN_PnLayout.setVerticalGroup(
            HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HHCN_PnLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(diemGocHHCN_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HHCN_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HHCN_PnLayout.createSequentialGroup()
                            .addComponent(xOHHCN_Lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(xOHHCN_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(HHCN_PnLayout.createSequentialGroup()
                            .addComponent(yOHHCN_Lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yOHHCN_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HHCN_PnLayout.createSequentialGroup()
                        .addComponent(zOHHCN_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zOHHCN_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(dai_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dai_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rong_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rong_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cao_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cao_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(veHHCN_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quayLai_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        tuyChon_LPn.add(HHCN_Pn, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xoaManHinh_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tuyChon_LPn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel3D, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tuyChon_LPn, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(xoaManHinh_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel3D, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("3D", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("2D", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel3DAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel3DAncestorAdded
        draw3DCoordinate();
        //drawGrid();
    }//GEN-LAST:event_panel3DAncestorAdded

    private void veHHCN_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veHHCN_BtnActionPerformed
        drawRectangular();
    }//GEN-LAST:event_veHHCN_BtnActionPerformed

    private void xoaManHinh_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaManHinh_BtnActionPerformed
        clear();
    }//GEN-LAST:event_xoaManHinh_BtnActionPerformed

    private void veHLP_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veHLP_BtnActionPerformed
        drawCube();
    }//GEN-LAST:event_veHLP_BtnActionPerformed

    private void HHCN_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HHCN_BtnActionPerformed
        changePanel(tuyChon_LPn, HHCN_Pn);
    }//GEN-LAST:event_HHCN_BtnActionPerformed

    private void HLP_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HLP_BtnActionPerformed
        changePanel(tuyChon_LPn, HLP_Pn);
    }//GEN-LAST:event_HLP_BtnActionPerformed

    private void quayLai_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLai_BtnActionPerformed
        changePanel(tuyChon_LPn, tuyChon_Pn);
    }//GEN-LAST:event_quayLai_BtnActionPerformed

    private void quayLai_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLai_Btn1ActionPerformed
        changePanel(tuyChon_LPn, tuyChon_Pn);
    }//GEN-LAST:event_quayLai_Btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HHCN_Btn;
    private javax.swing.JPanel HHCN_Pn;
    private javax.swing.JButton HLP_Btn;
    private javax.swing.JPanel HLP_Pn;
    private javax.swing.JLabel cao_Lbl;
    private javax.swing.JTextField cao_TF;
    private javax.swing.JLabel dai_Lbl;
    private javax.swing.JTextField dai_TF;
    private javax.swing.JLabel diemGocHHCN_Lbl;
    private javax.swing.JLabel diemGocHLP_Lbl;
    private javax.swing.JLabel doDaiCanhHLP_Lbl;
    private javax.swing.JTextField doDaiCanhHLP_TF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel3D;
    private javax.swing.JButton quayLai_Btn;
    private javax.swing.JButton quayLai_Btn1;
    private javax.swing.JLabel rong_Lbl;
    private javax.swing.JTextField rong_TF;
    private javax.swing.JLayeredPane tuyChon_LPn;
    private javax.swing.JPanel tuyChon_Pn;
    private javax.swing.JButton veHHCN_Btn;
    private javax.swing.JButton veHLP_Btn;
    private javax.swing.JLabel xOHHCN_Lbl;
    private javax.swing.JTextField xOHHCN_TF;
    private javax.swing.JLabel xOHLP_Lbl;
    private javax.swing.JTextField xOHLP_TF;
    private javax.swing.JButton xoaManHinh_Btn;
    private javax.swing.JLabel yOHHCN_Lbl;
    private javax.swing.JTextField yOHHCN_TF;
    private javax.swing.JLabel yOHLP_Lbl;
    private javax.swing.JTextField yOHLP_TF;
    private javax.swing.JLabel zOHHCN_Lbl;
    private javax.swing.JTextField zOHHCN_TF;
    private javax.swing.JLabel zOHLP_Lbl;
    private javax.swing.JTextField zOHLP_TF;
    // End of variables declaration//GEN-END:variables

    public void changePanel(JLayeredPane jLayeredPane,JPanel panel){
        jLayeredPane.removeAll();
        jLayeredPane.add(panel);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }    
    
    public void clear()
    {
        g3D.clearRect(0, 0, width, height);
//        panel3D.setBackground(Color.white);
        g3D = panel3D.getGraphics();       
        draw3DCoordinate();
    }
    
    public void draw3DCoordinate()
    {
        height = panel3D.getBounds().height; // Lay chieu cao cua Panel
        width = panel3D.getBounds().width; // Lay chieu dai cua Panel
        
        g3D.setColor(Color.BLACK);
        g3D.drawLine(width/2, height/2, width, height/2); // Ve truc Ox
        g3D.drawLine(width/2, 0, width/2, height/2); // Ve truc Oz       
        g3D.drawLine(width/2, height/2, 0, width/2 + height/2); // Ve truc Oy

        int x1 = 4;
        for (int i = 0 ; i <= width/2; i++)
        {
            if (i % (3*x1) == 2*x1)
            {
                g3D.drawLine(i, height/2, i - 2*x1, height/2); // Ox'
            }
        }
        for (int i = height + 1 ; i >= height/2; i--)
        {
            int x = height - i;
            if (x % (3*x1) == 2*x1)
            {
                g3D.drawLine(width/2, i, width/2, i - 2*x1); // Oy'
            }
        }        
        for (int i = width/2 ; i <= width; i++)
        {
            int x = i - width/2;
            if (x % (3*x1) == 2*x1)
            {
                g3D.drawLine(i, height/2 - x, i - 2*x1, height/2 - (x - 2*x1)); // Oz'
            }
        }        
        
//        int inc = 1; // Don vi duong
//        int desc = -1; // Don vi am        
//        for (int i = 0; i < width; i += step) 
//        {
//            g3D.setColor(Color.BLACK);
//            g3D.drawLine(width/2 + i, height/2 - 2, width/2 + i, height/2 + 2); // Ve cac gach cua Ox
//            g3D.drawLine(width/2 - i, height/2 - 2, width/2 - i, height/2 + 2); // Ve cac gach cua Ox'
//            g3D.drawLine(width/2 - 2, height/2 - i, width/2 + 2, height/2 - i); // Ve cac gach cua Oy
//            g3D.drawLine(width/2 - 2, height/2 + i, width/2 + 2, height/2 + i); // Ve cac gach cua Oy'
//            
//            
//            g3D.setColor(Color.BLUE);
//            g3D.drawString(String.valueOf(inc), width/2 + i + step - 3, height/2 + 15); // Danh so don vi cho Ox
//            g3D.drawString(String.valueOf(desc), width/2 - i - step - 7, height/2 + 15); // Danh so don vi cho Ox'
//            g3D.drawString(String.valueOf(inc), width/2 - 15, height/2 - i - step + 5); // Danh so don vi cho Oy
//            g3D.drawString(String.valueOf(desc), width/2 - 15, height/2 + i + step + 5); // Danh so don vi cho Oy'
//            
//            inc++;
//            desc--;         
//        }    
        g3D.setColor(Color.blue);
        g3D.drawString("x", width - 20, height/2 - 10);
        g3D.drawString("z", width/2 + 10, 0 + 10);
        g3D.drawString("O", width/2 - 15, height/2 + 15);      
        g3D.drawString("y", width/4 - 25, height - 5);
    }
    
    
    // De khong bi mat do thi khi zoom len hay di chuyen frame
    @Override
    public void paint(Graphics g) 
    {
        super.paint(g);
        draw3DCoordinate();
    }
        
    public void putPixel(double x, double y)
    {       
        Graphics2D g1 = (Graphics2D) g3D.create();
        g1.setColor(Color.BLACK);
        g1.fillRect((int)x, (int)y, 3,3);       
    }    
    
    public void putPixel3D(double x, double y)
    {       
        Graphics2D g1 = (Graphics2D) g3D.create();
        g1.setColor(Color.RED);
        
        // Dua ve goc toa do
        double newX = x*step + width/2;
        double newY = height/2 - y*step;
                
        g1.fillRect((int)newX, (int)newY, 4, 4);       
    }  
    
    public void putText3D(String tenDiem, int x, int y, int z)
    {
        Graphics2D g1 = (Graphics2D) g3D.create();
        
        double newX, newY;  
        newX =  cavalierProjection(x, y)*step + width/2; 
        newY = height/2 - cavalierProjection(z, y)*step; 
               
        g1.setColor(Color.black);
        g1.drawString(tenDiem + "(" + x + "," + y + "," + z + ")",(int)newX + 5,(int)newY + 10);
    }        
    
    public double cavalierProjection(double a, double b)
    {
        // Chieu len truc Oxz
        return a - b*(1 - Math.sqrt(2)/2);
    }      
    
    public void drawGrid()
    {
        g3D.setColor(Color.black);
        
        // Luoi doc
        for (int x = 0; x < width; x += step)
        {
            g3D.drawLine(x, 0, x, height);
        }

        // Luoi ngang
        for (int y = 0; y < height; y += step)
        {
            g3D.drawLine(0, y, width, y);
        }
    }

    public void drawLineDDA(double x1, double y1, double x2, double y2)
    {   
        // Dua ve tam toa do
        x1 = x1*this.step + width/2;
        y1 = height/2 - y1*this.step;        
        x2 = x2*this.step + width/2;
        y2 = height/2 - y2*this.step;           
        
        double dx = x2 - x1;
        double dy = y2 - y1;  
        double step;
        if(Math.abs(dx) >= Math.abs(dy))
        {
            step = Math.abs(dx);
        } 
        else
        {
            step = Math.abs(dy);
        }
        double x_inc = dx/step;
        double y_inc = dy/step;
        
        double x = x1;
        double y = y1;
        putPixel(x, y);

        for (int i = 0; i <= step; i++)
        {
            x = x + x_inc;
            y = y + y_inc;
            putPixel(Math.round(x), Math.round(y));
        }
    }
   
    public void drawDashedLineDDA(double x1, double y1, double x2, double y2)
    {   
        // Dua ve tam toa do
        x1 = x1*this.step + width/2;
        y1 = height/2 - y1*this.step;        
        x2 = x2*this.step + width/2;
        y2 = height/2 - y2*this.step;           
        
        double dx = x2 - x1;
        double dy = y2 - y1;  
        double step;
        if(Math.abs(dx) >= Math.abs(dy))
        {
            step = Math.abs(dx);
        } 
        else
        {
            step = Math.abs(dy);
        }
        double x_inc = dx/step;
        double y_inc = dy/step;
        
        double x = x1;
        double y = y1;
        putPixel(x, y);

        // Dem so pixel da put. Khi dat den 1 so luong nhat dinh thi ngung khong put nua
        int count = 0;
        for (int i = 0; i <= step; i++)
        {
            count++;
            if (count <= 10) // put 10 pixel
            {
                putPixel(Math.round(x), Math.round(y));
                x = x + x_inc;
                y = y + y_inc;
            }
            else if (count >= 11 && count <= 15) // 5 pixel tiep theo khong put
            {
                x = x + x_inc;
                y = y + y_inc;
                if (count == 15)
                {
                    count = 0; // Lap lai viec put pixel
                }
            }
        }
    }
    
    public void drawDDAWithCondition(double x1, double y1, double x2, double y2, String circumstance)
    {
        if (circumstance.equals("Straight"))
        {
            if (x1 > x2)
            {
                drawLineDDA(x2, y2, x1, y1);
            }
            else
            {
               drawLineDDA(x1, y1, x2, y2);
            }        
        }
        else if (circumstance.equals("Dashed"))
        {
            if (x1 > x2)
            {
                drawDashedLineDDA(x2, y2, x1, y1);
            }
            else
            {
                drawDashedLineDDA(x1, y1, x2, y2);
            }                 
        }
    }
    
    public void drawRectangular()
    {
        // Diem goc O
        double xO = Double.valueOf(xOHHCN_TF.getText());
        double yO = Double.valueOf(yOHHCN_TF.getText());
        double zO = Double.valueOf(zOHHCN_TF.getText());      
        
        double xO1 = cavalierProjection(xO, yO);
        double yO1 = cavalierProjection(zO, yO);
        
        // A
        double xA = Double.valueOf(dai_TF.getText()) + xO;
        double yA = 0 + yO;
        double zA = 0 + zO;
        
        double xA1 = cavalierProjection(xA, yA);
        double yA1 = cavalierProjection(zA, yA);
        
        // B
        double xB = Double.valueOf(dai_TF.getText()) + xO;
        double yB = Double.valueOf(rong_TF.getText()) + yO;
        double zB = 0 + zO;
        
        double xB1 = cavalierProjection(xB, yB);
        double yB1 = cavalierProjection(zB, yB);
        
        // C
        double xC = 0 + xO;
        double yC = Double.valueOf(rong_TF.getText()) + yO;
        double zC = 0 + zO;
        
        double xC1 = cavalierProjection(xC, yC);
        double yC1 = cavalierProjection(zC, yC);
        
        // D
        double xD = Double.valueOf(dai_TF.getText()) + xO;
        double yD = 0 + yO;
        double zD = Double.valueOf(cao_TF.getText()) + zO;
        
        double xD1 = cavalierProjection(xD, yD);
        double yD1 = cavalierProjection(zD, yD);    
        
        // E 
        double xE = 0 + xO;
        double yE = 0 + yO;
        double zE = Double.valueOf(cao_TF.getText()) + zO;
        
        double xE1 = cavalierProjection(xE, yE);
        double yE1 = cavalierProjection(zE, yE);    
        
        // F
        double xF = 0 + xO;
        double yF = Double.valueOf(rong_TF.getText()) + yO;
        double zF = Double.valueOf(cao_TF.getText()) + zO;
        
        double xF1 = cavalierProjection(xF, yF);
        double yF1 = cavalierProjection(zF, yF);      
        
        // G
        double xG = Double.valueOf(dai_TF.getText()) + xO;
        double yG = Double.valueOf(rong_TF.getText()) + yO;
        double zG = Double.valueOf(cao_TF.getText()) + zO;
        
        double xG1 = cavalierProjection(xG, yG);
        double yG1 = cavalierProjection(zG, yG);        
           
        putPixel3D(xO1, yO1);
        putPixel3D(xA1, yA1);
        putPixel3D(xB1, yB1);
        putPixel3D(xC1, yC1);
        putPixel3D(xD1, yD1);
        putPixel3D(xE1, yE1);
        putPixel3D(xF1, yF1);
        putPixel3D(xG1, yG1);
        
        putText3D("O", (int)xO, (int)yO, (int)zO); 
        putText3D("A", (int)xA, (int)yA, (int)zA);        
        putText3D("B", (int)xB, (int)yB, (int)zB);   
        putText3D("C", (int)xC, (int)yC, (int)zC); 
        putText3D("D", (int)xD, (int)yD, (int)zD);
        putText3D("E", (int)xE, (int)yE, (int)zE);
        putText3D("F", (int)xF, (int)yF, (int)zF);
        putText3D("G", (int)xG, (int)yG, (int)zG); 
        
        drawDDAWithCondition(xA1, yA1, xB1, yB1, "Straight"); // AB
        drawDDAWithCondition(xA1, yA1, xD1, yD1, "Straight"); // AD
        drawDDAWithCondition(xB1, yB1, xC1, yC1, "Straight"); // BC
        drawDDAWithCondition(xB1, yB1, xG1, yG1, "Straight"); // BG       
        drawDDAWithCondition(xC1, yC1, xF1, yF1, "Straight"); // CF
        drawDDAWithCondition(xD1, yD1, xG1, yG1, "Straight"); // DG
        drawDDAWithCondition(xE1, yE1, xF1, yF1, "Straight"); // EF        
        drawDDAWithCondition(xE1, yE1, xD1, yD1, "Straight"); // ED        
        drawDDAWithCondition(xF1, yF1, xG1, yG1, "Straight"); // FG
        
        drawDDAWithCondition(xO1, yO1, xC1, yC1, "Dashed"); // OC
        drawDDAWithCondition(xO1, yO1, xA1, yA1, "Dashed"); // OA
        drawDDAWithCondition(xO1, yO1, xE1, yE1, "Dashed"); // EO
    }  
    
    public void drawCube()
    {
        // Diem goc O
        double xO = Double.valueOf(xOHLP_TF.getText());
        double yO = Double.valueOf(yOHLP_TF.getText());
        double zO = Double.valueOf(zOHLP_TF.getText());              
  
        double xO1 = cavalierProjection(xO, yO);
        double yO1 = cavalierProjection(zO, yO);        
        
        // A
        double xA = Double.valueOf(doDaiCanhHLP_TF.getText()) + xO;
        double yA = 0 + yO;
        double zA = 0 + zO;
        
        double xA1 = cavalierProjection(xA, yA);
        double yA1 = cavalierProjection(zA, yA);
        
        // B
        double xB = Double.valueOf(doDaiCanhHLP_TF.getText()) + xO;
        double yB = Double.valueOf(doDaiCanhHLP_TF.getText()) + yO;
        double zB = 0 + zO;
        
        double xB1 = cavalierProjection(xB, yB);
        double yB1 = cavalierProjection(zB, yB);
        
        // C
        double xC = 0 + xO;
        double yC = Double.valueOf(doDaiCanhHLP_TF.getText()) + yO;
        double zC = 0 + zO;
        
        double xC1 = cavalierProjection(xC, yC);
        double yC1 = cavalierProjection(zC, yC);
        
        // D
        double xD = Double.valueOf(doDaiCanhHLP_TF.getText()) + xO;
        double yD = 0 + yO;
        double zD = Double.valueOf(doDaiCanhHLP_TF.getText()) + zO;
        
        double xD1 = cavalierProjection(xD, yD);
        double yD1 = cavalierProjection(zD, yD);    
        
        // E 
        double xE = 0 + xO;
        double yE = 0 + yO;
        double zE = Double.valueOf(doDaiCanhHLP_TF.getText()) + zO;
        
        double xE1 = cavalierProjection(xE, yE);
        double yE1 = cavalierProjection(zE, yE);    
        
        // F
        double xF = 0 + xO;
        double yF = Double.valueOf(doDaiCanhHLP_TF.getText()) + yO;
        double zF = Double.valueOf(doDaiCanhHLP_TF.getText()) + zO;
        
        double xF1 = cavalierProjection(xF, yF);
        double yF1 = cavalierProjection(zF, yF);      
        
        // G
        double xG = Double.valueOf(doDaiCanhHLP_TF.getText()) + xO;
        double yG = Double.valueOf(doDaiCanhHLP_TF.getText()) + yO;
        double zG = Double.valueOf(doDaiCanhHLP_TF.getText()) + zO;
        
        double xG1 = cavalierProjection(xG, yG);
        double yG1 = cavalierProjection(zG, yG);        
           
        putPixel3D(xO1, yO1);
        putPixel3D(xA1, yA1);
        putPixel3D(xB1, yB1);
        putPixel3D(xC1, yC1);
        putPixel3D(xD1, yD1);
        putPixel3D(xE1, yE1);
        putPixel3D(xF1, yF1);
        putPixel3D(xG1, yG1);
        
        putText3D("O", (int)xO, (int)yO, (int)zO); 
        putText3D("A", (int)xA, (int)yA, (int)zA);        
        putText3D("B", (int)xB, (int)yB, (int)zB);   
        putText3D("C", (int)xC, (int)yC, (int)zC); 
        putText3D("D", (int)xD, (int)yD, (int)zD);
        putText3D("E", (int)xE, (int)yE, (int)zE);
        putText3D("F", (int)xF, (int)yF, (int)zF);
        putText3D("G", (int)xG, (int)yG, (int)zG); 
        
        drawDDAWithCondition(xA1, yA1, xB1, yB1, "Straight"); // AB
        drawDDAWithCondition(xA1, yA1, xD1, yD1, "Straight"); // AD
        drawDDAWithCondition(xB1, yB1, xC1, yC1, "Straight"); // BC
        drawDDAWithCondition(xB1, yB1, xG1, yG1, "Straight"); // BG       
        drawDDAWithCondition(xC1, yC1, xF1, yF1, "Straight"); // CF
        drawDDAWithCondition(xD1, yD1, xG1, yG1, "Straight"); // DG
        drawDDAWithCondition(xE1, yE1, xF1, yF1, "Straight"); // EF        
        drawDDAWithCondition(xE1, yE1, xD1, yD1, "Straight"); // ED        
        drawDDAWithCondition(xF1, yF1, xG1, yG1, "Straight"); // FG
        
        drawDDAWithCondition(xO1, yO1, xC1, yC1, "Dashed"); // OC
        drawDDAWithCondition(xO1, yO1, xA1, yA1, "Dashed"); // OA
        drawDDAWithCondition(xO1, yO1, xE1, yE1, "Dashed"); // EO        
    }
}
